/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/forestRuins.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forestRuins.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[16.544, 2.16, 16.544]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.verde2} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.suelo} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.verdeBase} position={[0, 2.456, 0]} scale={[12.876, 0.333, 11.759]} />
      <group position={[-17.307, 0.913, 2.336]} scale={[6.638, 0.172, 8.969]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.verde2} />
      </group>
      <group position={[-17.307, -1.18, -13.905]} scale={[20.14, 0.172, 9.141]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.verde2} />
      </group>
      <group position={[-17.307, -1.221, -7.113]} scale={[6.638, 0.172, 3.602]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.verde2} />
      </group>
      <group position={[-17.307, -0.151, 13.223]} scale={[6.638, 0.172, 3.602]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.verde2} />
      </group>
      <group position={[-10.136, -0.151, 17.662]} scale={[15.11, 0.172, 3.602]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.verde2} />
      </group>
      <group position={[4.149, 0.796, 17.662]} scale={[23.211, 0.172, 3.602]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.verde2} />
      </group>
      <group position={[12.655, -1.426, 16.083]} scale={[23.211, 0.503, 10.078]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials.verde2} />
      </group>
      <group position={[14.737, -21.164, -18.123]} scale={[56.047, 1.214, 24.336]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube009_3.geometry} material={materials.verde2} />
      </group>
      <mesh geometry={nodes.Cube011.geometry} material={materials.MADERA} position={[-18.917, 9.166, -14.297]} scale={[-0.118, -11.092, -0.118]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.MADERA} position={[-17.341, 3.76, 13.172]} scale={[-0.118, -3.638, -0.118]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.verdeBase} position={[-17.355, 7.398, 13.217]} scale={[1.092, 0.458, 2.559]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.verde2} position={[-17.355, 6.765, 13.217]} scale={[1.442, 0.218, 1.843]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.verdeBase} position={[-18.448, 7.465, 11.845]} scale={0.258} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.verde2} position={[-17.053, 8.056, 12.714]} scale={[0.47, 0.258, 1.208]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.verde2} position={[-16.168, 7.384, 15.354]} scale={0.58} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.verde2} position={[-18.97, 20.766, -14.236]} scale={[2.46, 1.032, 5.76]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.verdeBase} position={[-17.731, 20.731, -10.576]} scale={[2.356, 0.357, 3.012]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.verde2} position={[-21.51, 20.437, -16.831]} scale={-1.027} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.verde2} position={[-18.292, 23.621, -15.369]} scale={[0.469, 0.257, 1.206]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.verdeBase} position={[-18.97, 21.817, -14.236]} scale={[1.744, 0.732, 4.085]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.verdeBase} position={[-1.662, 31.756, -8.723]} scale={[2.55, 1.07, 7.947]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.verde2} position={[-1.662, 30.278, -8.723]} scale={[3.365, 0.51, 6.491]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.verdeBase} position={[-4.214, 31.911, -11.925]} scale={[0.601, 0.601, 1.649]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.verdeBase} position={[-1.642, 33.291, -12.884]} scale={[1.097, 0.601, 2.82]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.MADERA} position={[-1.646, 14.224, -8.647]} scale={[-0.118, -16.501, -0.118]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.verde2} position={[-4.96, 30.268, -4.675]} scale={0.341} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.verde2} position={[-1.642, 33.291, -5.202]} scale={[1.097, 0.601, 2.82]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.verde2} position={[0.433, 34.899, -5.202]} scale={[0.462, 0.253, 1.187]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.verde2} position={[-4.062, 34.553, -13.797]} scale={[0.462, 0.253, 0.422]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.verdeBase} position={[-1.513, 4.294, -8.725]} scale={2.572} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.MADERA} position={[-1.634, 18.274, -7.688]} rotation={[0.78, 0, 0]} scale={[-0.118, -1.459, -0.084]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.MADERA} position={[-1.634, 15.943, -9.621]} rotation={[2.439, 0, 0]} scale={[-0.118, -1.459, -0.084]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.verdeBase} position={[-1.911, 17.466, -11.077]} scale={[0.662, 0.278, 1.551]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.verde2} position={[-1.911, 17.082, -11.077]} scale={[0.874, 0.132, 1.118]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.verdeBase} position={[-2.574, 17.507, -11.909]} scale={0.156} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.verde2} position={[-1.728, 17.832, -10.251]} scale={[0.285, 0.156, 0.733]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials.verde2} position={[-1.662, 29.563, -8.723]} scale={[2.442, 0.37, 4.71]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials.MADERA} position={[-19.85, 12.907, -14.271]} rotation={[1.561, -0.868, -1.583]} scale={[-0.118, -1.459, -0.084]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.MADERA} position={[8.473, 10.333, 6.138]} scale={[-0.118, -7.864, -0.118]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.verdeBase} position={[8.443, 18.905, 6.061]} scale={[1.318, 0.553, 3.086]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.verde2} position={[8.443, 18.141, 6.061]} scale={[1.739, 0.263, 2.223]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.verdeBase} position={[7.124, 18.985, 4.406]} scale={0.311} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.verde2} position={[8.806, 19.698, 5.454]} scale={[0.567, 0.311, 1.457]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.verde2} position={[9.875, 18.888, 8.639]} scale={0.699} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.MADERA} position={[-3.57, 9.012, -10.07]} scale={[-0.118, -3.638, -0.118]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials.verdeBase} position={[-3.584, 12.65, -10.025]} scale={[1.092, 0.458, 2.559]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials.verde2} position={[-3.584, 12.017, -10.025]} scale={[1.442, 0.218, 1.843]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials.verdeBase} position={[-4.677, 12.717, -11.397]} scale={0.258} />
      <mesh geometry={nodes.Cube056.geometry} material={materials.verde2} position={[-3.282, 13.308, -10.528]} scale={[0.47, 0.258, 1.208]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials.verde2} position={[-2.397, 12.637, -7.888]} scale={0.58} />
      <mesh geometry={nodes.Cube058.geometry} material={materials.verdeBase} position={[12.36, 21.441, 18.403]} rotation={[Math.PI, -0.008, Math.PI]} scale={[2.55, 1.07, 7.947]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials.verde2} position={[12.36, 19.963, 18.403]} rotation={[Math.PI, -0.008, Math.PI]} scale={[3.365, 0.51, 6.491]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials.verdeBase} position={[14.938, 21.596, 21.585]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.601, 0.601, 1.649]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials.verdeBase} position={[12.373, 22.976, 22.565]} rotation={[Math.PI, -0.008, Math.PI]} scale={[1.097, 0.601, 2.82]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials.MADERA} position={[12.343, 9.315, 18.327]} rotation={[Math.PI, -0.008, Math.PI]} scale={[-0.118, -10.312, -0.118]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials.verde2} position={[15.624, 19.954, 14.328]} rotation={[Math.PI, -0.008, Math.PI]} scale={0.341} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.verde2} position={[12.31, 22.976, 14.882]} rotation={[Math.PI, -0.008, Math.PI]} scale={[1.097, 0.601, 2.82]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials.verde2} position={[10.236, 24.584, 14.899]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.462, 0.253, 1.187]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials.verde2} position={[14.801, 24.238, 23.458]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.462, 0.253, 0.422]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials.verde2} position={[12.36, 19.248, 18.403]} rotation={[Math.PI, -0.008, Math.PI]} scale={[2.442, 0.37, 4.71]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials.MADERA} position={[12.366, 17.654, 20.014]} rotation={[0.78, 0, 0]} scale={[-0.118, -2.468, -0.084]} />
      <mesh geometry={nodes.Cube069.geometry} material={materials.MADERA} position={[11.865, 12.587, -13.622]} rotation={[2.157, 0.005, -Math.PI]} scale={[-0.1, -1.346, -0.1]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials.verdeBase} position={[11.925, 22.097, -10.386]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={[2.714, 1.139, 6.357]} />
      <mesh geometry={nodes.Cube071.geometry} material={materials.verde2} position={[11.925, 20.523, -10.386]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={[3.582, 0.542, 4.579]} />
      <mesh geometry={nodes.Cube072.geometry} material={materials.verdeBase} position={[14.626, 22.262, -6.964]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={0.64} />
      <mesh geometry={nodes.Cube073.geometry} material={materials.verde2} position={[11.171, 23.73, -9.139]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={[1.168, 0.64, 3.002]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials.verde2} position={[9, 22.062, -15.708]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={1.44} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.MADERA} position={[12.366, 7.601, 18.557]} rotation={[-2.361, 0, Math.PI]} scale={[0.118, 0.367, 0.084]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.MADERA} position={[12.366, 9.263, 17.42]} rotation={[2.456, 0, 0]} scale={[-0.118, -1.468, -0.084]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials.verdeBase} position={[11.822, 10.931, 16.146]} scale={[0.662, 0.278, 1.551]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.verde2} position={[11.822, 10.547, 16.146]} scale={[0.874, 0.132, 1.118]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials.verde2} position={[12.005, 11.296, 16.971]} scale={[0.285, 0.156, 0.733]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials.MADERA} position={[8.494, 13.427, 5.851]} rotation={[-0.686, 0, -Math.PI]} scale={[0.118, 0.484, 0.084]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials.MADERA} position={[8.494, 9.87, 5.851]} rotation={[-0.686, 0, -Math.PI]} scale={[0.118, 0.484, 0.084]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials.MADERA} position={[11.865, 11.078, -12.441]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={[-0.139, -9.318, -0.139]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials.verde2} position={[11.745, 19.645, -12.233]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={[1.805, 0.273, 2.307]} />
      <mesh geometry={nodes.Cube078.geometry} material={materials.MADERA} position={[11.865, 9.877, -11.426]} rotation={[0.818, 0.005, -Math.PI]} scale={[-0.1, -1.346, -0.1]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials.suelo} position={[-12.402, 1.138, 13.484]} scale={-1.758} />
      <mesh geometry={nodes.Cube080.geometry} material={materials.suelo} position={[-12.44, 2.519, -10.61]} rotation={[Math.PI, -0.412, Math.PI]} scale={-0.867} />
      <mesh geometry={nodes.Cube081.geometry} material={materials.suelo} position={[-10.032, -0.597, 17.672]} scale={-0.943} />
      <mesh geometry={nodes.Cube082.geometry} material={materials.ouranure} position={[2.212, 2.795, 1.732]} scale={[4.812, 1.004, 4.812]} />
      <group position={[-1.089, 7.509, -1.702]} scale={[0.5, 3.008, 0.5]}>
        <mesh geometry={nodes.Cube095_1.geometry} material={materials.ouranure} />
        <mesh geometry={nodes.Cube095_2.geometry} material={materials.MADERA} />
      </group>
      <group position={[-1.089, 7.509, 5.544]} scale={[0.5, 3.008, 0.5]}>
        <mesh geometry={nodes.Cube096_1.geometry} material={materials.ouranure} />
        <mesh geometry={nodes.Cube096_2.geometry} material={materials.MADERA} />
      </group>
      <mesh geometry={nodes.Cube085.geometry} material={materials.ouranure} position={[-1.089, 7.529, 4.254]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube086.geometry} material={materials.ouranure} position={[-1.089, 7.548, -0.412]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube087.geometry} material={materials.ouranure} position={[0.14, 7.566, 5.544]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube088.geometry} material={materials.ouranure} position={[4.6, 7.48, 5.544]} scale={[0.5, 3.008, 0.5]} />
      <group position={[5.829, 7.537, 5.544]} scale={[0.5, 3.008, 0.5]}>
        <mesh geometry={nodes.Cube101_1.geometry} material={materials.ouranure} />
        <mesh geometry={nodes.Cube101_2.geometry} material={materials.MADERA} />
      </group>
      <mesh geometry={nodes.Cube090.geometry} material={materials.ouranure} position={[0.14, 7.427, -1.682]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube091.geometry} material={materials.ouranure} position={[4.6, 7.341, -1.682]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube092.geometry} material={materials.ouranure} position={[5.829, 7.398, -1.682]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[5.829, 7.481, -0.425]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube094.geometry} material={nodes.Cube094.material} position={[5.829, 7.597, 4.323]} scale={[0.5, 3.008, 0.5]} />
      <mesh geometry={nodes.Cube095.geometry} material={materials.MADERA} position={[2.218, 11.859, -1.748]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube096.geometry} material={materials.MADERA} position={[2.218, 11.859, -0.366]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube097.geometry} material={materials.MADERA} position={[2.218, 11.859, 5.554]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube098.geometry} material={materials.MADERA} position={[2.218, 11.843, 3.982]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube099.geometry} material={materials.MADERA} position={[2.218, 11.843, 2.493]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube100.geometry} material={materials.MADERA} position={[2.218, 11.859, 1.037]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube101.geometry} material={materials.MADERA} position={[5.689, 11.859, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube102.geometry} material={materials.MADERA} position={[4.346, 11.859, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube103.geometry} material={materials.MADERA} position={[-1.404, 11.859, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube104.geometry} material={materials.MADERA} position={[0.123, 11.843, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube105.geometry} material={materials.MADERA} position={[1.569, 11.843, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube106.geometry} material={materials.MADERA} position={[2.983, 11.859, 1.98]} rotation={[0, Math.PI / 2, 0]} scale={[4.891, 0.555, 0.555]} />
      <mesh geometry={nodes.Cube107.geometry} material={materials.ouranure} position={[-3.59, 2.936, 1.98]} scale={[1.213, 0.218, 1.546]} />
      <mesh geometry={nodes.Cube108.geometry} material={materials.verdeBase} position={[10.246, 1.357, 9.571]} scale={2.572} />
      <mesh geometry={nodes.Cube109.geometry} material={materials.suelo} position={[0.37, 6, -7.621]} rotation={[Math.PI, -0.412, Math.PI]} scale={-0.867} />
      <group position={[2.842, -14.668, 17.938]} scale={[56.047, 1.214, 24.336]}>
        <mesh geometry={nodes.Cube122.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube122_1.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube122_2.geometry} material={materials.verde2} />
      </group>
      <group position={[-15.096, -4.879, 15.205]} scale={[23.503, 0.509, 10.205]}>
        <mesh geometry={nodes.Cube123.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube123_1.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube123_2.geometry} material={materials.verde2} />
      </group>
      <group position={[-8.796, -4.307, -36.789]} scale={[23.503, 0.509, 10.205]}>
        <mesh geometry={nodes.Cube124.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube124_1.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube124_2.geometry} material={materials.verde2} />
      </group>
      <group position={[-2.38, -28.697, -28.278]} scale={[56.047, 1.214, 24.336]}>
        <mesh geometry={nodes.Cube125.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube125_1.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube125_2.geometry} material={materials.verde2} />
      </group>
      <group position={[-15.096, -1.567, 37.784]} scale={[16.75, 0.363, 7.273]}>
        <mesh geometry={nodes.Cube126.geometry} material={materials.verdeBase} />
        <mesh geometry={nodes.Cube126_1.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Cube126_2.geometry} material={materials.verde2} />
      </group>
      <mesh geometry={nodes.Cube115.geometry} material={materials.MADERA} position={[-7.511, -25.449, -30.276]} scale={[-0.118, -11.092, -0.118]} />
      <mesh geometry={nodes.Cube116.geometry} material={materials.verde2} position={[-7.564, -13.849, -30.215]} scale={[2.46, 1.032, 5.76]} />
      <mesh geometry={nodes.Cube117.geometry} material={materials.verdeBase} position={[-6.325, -13.884, -26.556]} scale={[2.356, 0.357, 3.012]} />
      <mesh geometry={nodes.Cube118.geometry} material={materials.verde2} position={[-10.104, -14.179, -32.811]} scale={-1.027} />
      <mesh geometry={nodes.Cube119.geometry} material={materials.verde2} position={[-6.886, -10.994, -31.348]} scale={[0.469, 0.257, 1.206]} />
      <mesh geometry={nodes.Cube120.geometry} material={materials.verdeBase} position={[-7.564, -12.798, -30.215]} scale={[1.744, 0.732, 4.085]} />
      <mesh geometry={nodes.Cube121.geometry} material={materials.suelo} position={[3.336, -10.685, 21.317]} scale={-2.938} />
    </group>
  )
}

useGLTF.preload('/forestRuins.glb')
