/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/paisaje.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/paisaje.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} scale={5.887} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.paredes} position={[-2.5, 7.128, 0]} />
      <group position={[-4.079, 13.185, 2.608]} rotation={[Math.PI, -0.963, Math.PI]}>
        <mesh geometry={nodes.Cube021_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.techos} />
      </group>
      <group position={[15.241, 4.904, 5.796]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials.techos} />
      </group>
      <group position={[15.241, 4.904, -5.797]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube019.geometry} material={materials.paredes} position={[1.975, 5.295, 7.978]} rotation={[0, 0.544, 0]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.techos} position={[0.059, 11.502, 0.047]} rotation={[0, -0.021, 0]} scale={1.467} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.001']} position={[-8.608, -10.181, 13.886]} scale={1.678} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.001']} position={[-6.854, -9.949, 10.672]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.001']} position={[-2.519, -9.517, 7.813]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.001']} position={[-22.357, -10.181, 13.886]} scale={1.678} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.001']} position={[-16.044, -16.269, 10.373]} scale={1.678} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.001']} position={[-5.163, -2.568, 17.407]} rotation={[0, -0.781, 0]} scale={2.434} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.001']} position={[6.393, -0.483, 16.16]} rotation={[-0.288, -0.102, 0.209]} scale={1.678} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.001']} position={[8.283, -9.742, -0.257]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.001']} position={[-2.519, -8.764, 5.293]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.001']} position={[-31.025, -13.116, 17.574]} rotation={[0, -0.514, 0]} scale={1.917} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.001']} position={[-0.294, -3.918, 16.749]} scale={[2.772, 1.699, 1.678]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.001']} position={[3.581, -10.682, -1.74]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.001']} position={[4.013, -16.175, -3.837]} scale={0.903} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.001']} position={[4.013, -15.911, -1.239]} scale={0.707} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.paredes} position={[-2.5, 16.392, 3.255]} scale={0.379} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.paredes} position={[0.183, 19.62, 1.543]} scale={0.379} />
      <group position={[12.135, -2.134, 5.752]} scale={1.457}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.techos} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.231, 16.553, -19.723]} rotation={[0, -0.126, 0]} scale={[1.457, 2.347, 1.457]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube007.geometry} material={materials.paredes} position={[10.015, 0, 0]} />
      <group position={[-17.274, 8.243, -9.344]} rotation={[-0.008, 0.99, 0.016]} scale={[1.699, 1.699, 1.689]}>
        <mesh geometry={nodes.Cube043_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials.techos} />
      </group>
      <group position={[-15.726, 14.282, 8.541]} rotation={[0, -0.486, 0]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube013.geometry} material={materials.paredes} position={[-10.796, 8.012, 16.474]} rotation={[0, 0.134, 0]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.paredes} position={[-27.707, 12.036, 3.77]} rotation={[0, 1.238, 0]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.paredes} position={[12.104, 7.523, -7.66]} rotation={[-Math.PI, 0.774, -Math.PI]} />
      <group position={[-14.845, 12.303, 1.002]} rotation={[0, -0.473, 0]} scale={1.457}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials.techos} />
      </group>
      <group position={[-2.958, 2.862, 9.331]} rotation={[0.014, -0.788, 0.01]} scale={1.037}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials.techos} />
      </group>
      <group position={[6.335, 2.862, 4.449]} rotation={[0.014, -0.788, 0.01]} scale={1.037}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.techos} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.paredes} />
      </group>
      <mesh geometry={nodes.Cube040.geometry} material={materials.paredes} position={[-0.104, 10.488, -19.6]} rotation={[-Math.PI, 0.059, -Math.PI]} />
      <group position={[-12.123, 6.356, -15.118]} rotation={[-0.008, 0.99, 0.016]} scale={1.037}>
        <mesh geometry={nodes.Cube044_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube044_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube042.geometry} material={materials.paredes} position={[-11.77, 14.828, -15.676]} rotation={[0, 0.99, 0]} />
      <group position={[-16.735, 12.636, -8.944]} rotation={[-0.008, 0.99, 0.016]} scale={[0.777, 0.777, 0.772]}>
        <mesh geometry={nodes.Cube046_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube046_2.geometry} material={materials.techos} />
      </group>
      <group position={[-16.454, 11.658, -20.4]} scale={1.457}>
        <mesh geometry={nodes.Cube047_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube047_2.geometry} material={materials.techos} />
      </group>
      <group position={[-20.309, 2.336, 25.001]} rotation={[0, 1.032, 0]} scale={1.457}>
        <mesh geometry={nodes.Cube049.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube049_1.geometry} material={materials.techos} />
      </group>
      <group position={[-2.5, 20.498, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.techos} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.paredes} />
      </group>
      <group position={[-2.381, 1.51, -0.129]} scale={7.898}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials.techos} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube047.geometry} material={materials['Material.001']} position={[-39.92, 8.218, 4.892]} scale={1.678} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Material.001']} position={[16.816, -19.241, -26.581]} scale={1.678} />
      <mesh geometry={nodes.Cube050.geometry} material={materials.paredes} position={[-10.97, 0, 8.831]} rotation={[Math.PI, -1.052, Math.PI]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.001']} position={[-18.745, -6.15, 25.665]} rotation={[2.946, 0.517, 0.125]} scale={2.68} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.001']} position={[-25.912, -16.93, 13.352]} rotation={[0, -0.514, 0]} scale={1.122} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.tronco} position={[14.242, 1.241, -25.921]} />
      <mesh geometry={nodes.Circle.geometry} material={materials.ARBOL} position={[13.735, 5.795, -38.334]} rotation={[0.176, 0, 0]} scale={4.616} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.tronco} position={[-36.219, 11.903, -0.299]} rotation={[-Math.PI, 0.058, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.tronco} position={[-35.208, 10.504, 3.892]} scale={0.494} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.tronco} position={[-40.291, 8.655, 12.082]} rotation={[Math.PI, -0.802, Math.PI]} scale={0.352} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-10.742, 0.756, 3.985]} rotation={[Math.PI, -1.31, Math.PI]} scale={5.887} />
      <group position={[-43.855, 21.682, 8.787]} scale={1.457}>
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[-30.898, 9.848, -24.385]} rotation={[-Math.PI, 1.526, -Math.PI]} scale={1.678} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.ARBOL} position={[-30.99, 25.465, -28.955]} rotation={[0, 0.823, 0]} scale={0.392} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.ARBOL} position={[-27.197, 13.534, -29.576]} rotation={[Math.PI, -1.557, Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.tronco} position={[-31.35, 29.381, -25.434]} rotation={[Math.PI, -1.281, Math.PI]} scale={0.393} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[-26.185, 12.134, -25.385]} rotation={[-Math.PI, 1.526, -Math.PI]} scale={0.494} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.paredes} position={[-30.638, 22.87, -22.06]} rotation={[Math.PI, -1.11, Math.PI]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Material.001']} position={[-15.156, -9.119, 17.964]} rotation={[0, 0, -0.123]} scale={0.648} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.001']} position={[1.288, -7.533, 19.252]} rotation={[0, 0.177, -0.123]} scale={0.485} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Material.001']} position={[13.541, -1.416, -8.946]} rotation={[0, 0.762, 0]} scale={1.678} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Material.001']} position={[10.908, -0.62, -11.784]} rotation={[0, 0.762, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.001']} position={[9.349, -5.076, -6.376]} rotation={[0, 0.762, 0]} scale={1.678} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Material.001']} position={[8.961, -3.873, -15.436]} rotation={[0, -0.019, 0]} scale={1.678} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Material.001']} position={[12.185, -1.432, -3.851]} rotation={[-0.355, 0.625, 0.453]} scale={1.678} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.001']} position={[12.151, -5.946, -6.338]} rotation={[0, 0.762, 0]} scale={1.678} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Material.001']} position={[-3.275, 27.544, -40.738]} scale={1.678} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Material.001']} position={[25.63, -0.585, -1.01]} rotation={[0, 0.94, -0.123]} scale={0.485} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Material.001']} position={[-5.189, 0, -8.348]} rotation={[0, 1.558, 0]} scale={5.887} />
      <group position={[-32.505, 25.824, -18.381]} rotation={[0, 1.178, 0]} scale={1.457}>
        <mesh geometry={nodes.Cube067_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube067_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.tronco} position={[-36.403, 25.04, -18.678]} rotation={[-Math.PI, 1.526, -Math.PI]} scale={0.393} />
      <group position={[-15.666, 16.757, 2.786]} rotation={[Math.PI, -1.038, Math.PI]}>
        <mesh geometry={nodes.Cube068_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube068_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.001']} position={[-18.649, 0.244, 13.731]} rotation={[0.007, -0.501, -0.066]} scale={1.678} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['Material.001']} position={[-41.619, 15.389, -8.663]} rotation={[0.007, -0.501, -0.189]} scale={1.202} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Material.001']} position={[-23.395, -0.226, 11.8]} rotation={[0.007, -0.501, -0.066]} scale={1.678} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['Material.001']} position={[-11.386, 1.469, 16.166]} rotation={[-0.341, -0.56, -0.019]} scale={1.678} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['Material.001']} position={[-20.94, -0.806, 13.265]} rotation={[0.007, -0.501, -0.066]} scale={1.678} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Material.001']} position={[-18.445, -3.069, 19.172]} rotation={[0.019, -0.324, -0.184]} scale={0.485} />
      <mesh geometry={nodes.Cube071.geometry} material={materials['Material.001']} position={[-39.934, 17.909, -6.04]} rotation={[-0.067, -0.492, -0.185]} scale={0.635} />
      <group position={[1.43, 18.417, 0]} rotation={[0, 1.571, 0]} scale={0.408}>
        <mesh geometry={nodes.Cube077_1.geometry} material={materials.paredes} />
        <mesh geometry={nodes.Cube077_2.geometry} material={materials.techos} />
      </group>
      <mesh geometry={nodes.Cube073.geometry} material={materials.paredes} position={[-0.535, 18.417, 3.404]} rotation={[0, Math.PI / 6, 0]} scale={0.408} />
      <mesh geometry={nodes.Cube074.geometry} material={materials.paredes} position={[-4.466, 18.417, 3.404]} rotation={[0, -Math.PI / 6, 0]} scale={0.408} />
      <mesh geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[-6.431, 18.417, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.408} />
      <mesh geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[-0.535, 18.417, -3.404]} rotation={[-Math.PI, Math.PI / 6, -Math.PI]} scale={0.408} />
      <mesh geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} position={[-4.466, 18.417, -3.404]} rotation={[Math.PI, -Math.PI / 6, Math.PI]} scale={0.408} />
      <mesh geometry={nodes.mainFloor.geometry} material={materials['Material.001']} position={[0, -6.653, 0]} scale={4.624} />
      <mesh geometry={nodes.Cube081.geometry} material={materials['Material.001']} position={[3.62, -37.312, 0.667]} rotation={[0.001, 0, 0.001]} scale={1.27} />
      <mesh geometry={nodes.Cube082.geometry} material={materials['Material.001']} position={[-2.831, -16.993, 9.938]} scale={3.042} />
      <mesh geometry={nodes.Cube083.geometry} material={materials['Material.001']} position={[-12.74, -16.658, 3.14]} rotation={[0, -0.781, 0]} scale={1.678} />
      <mesh geometry={nodes.Cube084.geometry} material={materials['Material.001']} position={[3.842, -12.804, 10.251]} rotation={[0.136, -0.046, 0.174]} scale={1.845} />
      <mesh geometry={nodes.Rock3.geometry} material={materials['Material.002']} position={[-21.578, -61.697, -4.716]} rotation={[0, 0, 3.057]} scale={1.471} />
      <mesh geometry={nodes.Rock1.geometry} material={materials['Material.002']} position={[2.955, -45.66, 13.5]} scale={1.471} />
      <mesh geometry={nodes.Rock2.geometry} material={materials['Material.002']} position={[8.776, -52.094, -13.332]} scale={1.471} />
      <mesh geometry={nodes.Cube088.geometry} material={materials['Material.001']} position={[-23.895, -4.808, 9.557]} rotation={[-2.966, 0.548, -0.178]} scale={4.149} />
      <mesh geometry={nodes.Cube089.geometry} material={materials['Material.001']} position={[-6.709, -9, 7.813]} rotation={[0, 0, -0.123]} scale={1.678} />
      <mesh geometry={nodes.Cube090.geometry} material={materials['Material.001']} position={[3.48, -4.971, 13.965]} scale={3.061} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.tronco} position={[-40.012, 23.835, 0.322]} rotation={[0, -0.793, 0]} scale={0.392} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials.ARBOL} position={[-40.012, 23.835, 0.322]} rotation={[0, -0.793, 0]} scale={0.392} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.tronco} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.ARBOL} position={[-41.175, 25.98, 5.399]} rotation={[-3.081, 1.192, 3.085]} scale={0.393} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials.ARBOL} position={[-35.208, 10.504, 3.892]} scale={0.494} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials.ARBOL} position={[-36.219, 11.903, -0.299]} rotation={[-Math.PI, 0.058, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials.ARBOL} position={[-36.219, 11.903, -0.299]} rotation={[-Math.PI, 0.058, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials.ARBOL} position={[-36.219, 11.903, -0.299]} rotation={[-Math.PI, 0.058, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials.ARBOL} position={[-40.291, 8.655, 12.082]} rotation={[Math.PI, -0.802, Math.PI]} scale={0.352} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials.ARBOL} position={[-36.403, 25.04, -18.678]} rotation={[-Math.PI, 1.526, -Math.PI]} scale={0.393} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials.ARBOL} position={[-31.35, 29.381, -25.434]} rotation={[Math.PI, -1.281, Math.PI]} scale={0.393} />
    </group>
  )
}

useGLTF.preload('/paisaje.glb')
