/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/404error.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

const Error404 = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/404error.glb");
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]].fadeOut(0.5);
    };
  }, [animationIndex]);
  return (
    <group
      {...props}
      ref={group}
      dispose={null}
      position={[40, 12, 20]}
      rotation={[0, 0, 0]}
    >
      <mesh
        geometry={nodes.Floor.geometry}
        material={materials.Wall}
        scale={9.377}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["4"]}
        position={[-1.304, 8.038, 0.019]}
        rotation={[0.661, 0.989, -0.625]}
        scale={2.094}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Wall}
        position={[0, 3.575, -3.693]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={9.398}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.Wall}
        position={[-2.467, 3.575, 0.039]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={9.424}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["4"]}
        position={[0.274, 8.031, -2.998]}
        rotation={[1.583, 0, 0]}
        scale={2.006}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[4.477, -0.084, -7.793]}
        scale={0.974}
      />
    </group>
  );
};

export default Error404;

useGLTF.preload("./models/404error.glb");
