/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/casaDonuts.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import gsap from "gsap";
// import { FLOOR_HEIGHT, NB_FLOORS } from "./Office";
import { useFrame } from "@react-three/fiber";

export const FLOOR_HEIGHT = 10;
export const NB_FLOORS = 5;

export function Paisaje(props) {
  const { nodes, materials } = useGLTF("./models/casaDonuts.glb");
  const ref = useRef();
  const tl = useRef();

  const scroll = useScroll();
  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useEffect(() => {
    tl.current = gsap.timeline();

    // vertical animation
    // tl.current.to(
    //   ref.current.position,
    //   {
    //     duration: 2,
    //     y: -FLOOR_HEIGHT * (NB_FLOORS - 3),
    //   },
    //   0
    // );

    tl.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: Math.PI / 6, z: 0 },
      0
    );
    tl.current.to(ref.current.rotation, { duration: 2, x: 0, y: 0, z: 0 }, 1);

    // Office movement
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        x: 60,
        z: -60,
      },
      0
    );
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        x: 70,
        z: 0,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 3),
      },
      1
    );
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        x: 0,
        z: 0,
        y: 0,
      },
      2
    );
  }, []);
  return (
    <group
      {...props}
      dispose={null}
      ref={ref}
      position={[0.5, -1, -1]}
      rotation={[0, -Math.PI / 3, 0]}
      receiveShadow
      castShadow
    >
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.004"]}
        position={[11.587, 0, 0]}
        rotation={[0, 0, -Math.PI]}
        scale={[-29.373, -0.144, -28.081]}
        receiveShadow
      />
      <group position={[0, 11.078, 0]} scale={[8.931, 10.926, 10.926]}>
        {/* modelo principal */}
        <mesh
          geometry={nodes.Cubo_1.geometry}
          material={materials.blenco}
          castShadow
        />
        <mesh geometry={nodes.Cubo_2.geometry} material={materials.marcios} />
        <mesh geometry={nodes.Cubo_3.geometry} material={materials.espejo} />
        <mesh
          geometry={nodes.Cubo_4.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <mesh
        geometry={nodes.Cubo001.geometry}
        material={materials.marcios}
        position={[8.644, 13.201, -4.401]}
        scale={[1.104, 1, 2.843]}
      />
      <mesh
        geometry={nodes.Cubo002.geometry}
        material={materials.marcios}
        position={[8.644, 13.201, 5.335]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.104, -1, -1.335]}
      />
      <group
        position={[6.58, 10.864, 20.793]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo005_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo005_2.geometry} material={materials.cafe} />
      </group>
      <mesh
        geometry={nodes.Cubo004.geometry}
        material={materials.marcios}
        position={[-0.064, 13.219, -10.529]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.148, 1, 4.086]}
      />
      <mesh
        geometry={nodes.Cubo006.geometry}
        material={materials.marcios}
        position={[7.156, 17.011, 0]}
        scale={[0.132, 0.132, 8.728]}
      />
      <mesh
        geometry={nodes.Cubo007.geometry}
        material={materials.marcios}
        position={[-0.429, 17.011, -8.75]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.132, 0.132, 5.157]}
      />
      <mesh
        geometry={nodes.Cubo008.geometry}
        material={materials.marcios}
        position={[-0.135, 18.387, -8.75]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.132, 0.132, 5.157]}
      />
      <group position={[5.778, 25.506, -7.863]}>
        <mesh geometry={nodes.Cubo010_1.geometry} material={materials.blenco} />
        <mesh geometry={nodes.Cubo010_2.geometry} material={materials.negro} />
      </group>
      <mesh
        geometry={nodes.Cubo010.geometry}
        material={materials.azulmate}
        position={[2.059, 26.271, 3.253]}
        scale={[2.597, 1, 4.236]}
      />
      <mesh
        geometry={nodes.Cubo012.geometry}
        material={materials["gris osciu.001"]}
        position={[4.326, 26.567, 5.446]}
        scale={[0.523, 0.032, 2.351]}
      />
      <mesh
        geometry={nodes.Cubo011.geometry}
        material={materials["gris osciu.001"]}
        position={[4.326, 26.942, 5.446]}
        scale={[0.523, 0.032, 2.351]}
      />
      <mesh
        geometry={nodes.Cubo013.geometry}
        material={materials["gris osciu.001"]}
        position={[4.326, 25.773, 5.446]}
        scale={[0.523, 0.032, 2.351]}
      />
      <mesh
        geometry={nodes.Cubo014.geometry}
        material={materials["gris osciu.001"]}
        position={[4.326, 26.149, 5.446]}
        scale={[0.523, 0.032, 2.351]}
      />
      <group position={[-6.227, 25.826, 7.26]} scale={0.381}>
        <mesh geometry={nodes.Cubo018_1.geometry} material={materials.blenco} />
        <mesh geometry={nodes.Cubo018_2.geometry} material={materials.negro} />
      </group>
      <group position={[-6.227, 25.826, -7.376]} scale={0.381}>
        <mesh geometry={nodes.Cubo019_1.geometry} material={materials.blenco} />
        <mesh geometry={nodes.Cubo019_2.geometry} material={materials.negro} />
      </group>
      <mesh
        geometry={nodes.Plano.geometry}
        material={materials.cortinas}
        position={[12.803, 9.804, -5.066]}
        scale={[3.45, 3.45, 5.001]}
      />
      <mesh
        geometry={nodes.Plano001.geometry}
        material={materials.cortinas}
        position={[12.803, 9.804, 5.037]}
        scale={3.45}
      />
      <mesh
        geometry={nodes.Cubo017.geometry}
        material={materials.marcios}
        position={[-0.135, 5.299, -10.068]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.132, 0.132, 5.157]}
      />
      <mesh
        geometry={nodes.Cubo003.geometry}
        material={materials.arbol}
        position={[8.655, 14.334, -6.172]}
        scale={0.128}
      />
      <mesh
        geometry={nodes.Cubo018.geometry}
        material={materials.arbol2}
        position={[8.655, 14.334, -3.895]}
        scale={0.089}
      />
      <mesh
        geometry={nodes.Cubo019.geometry}
        material={materials.arbol2}
        position={[8.655, 14.334, -3.229]}
        scale={0.107}
      />
      <mesh
        geometry={nodes.Cubo020.geometry}
        material={materials.arbol2}
        position={[8.655, 14.334, 5.334]}
        scale={0.107}
      />
      <mesh
        geometry={nodes.Cubo021.geometry}
        material={materials.arbol2}
        position={[2.68, 14.334, -10.564]}
        scale={[0.128, 0.058, 0.128]}
      />
      <mesh
        geometry={nodes.Cubo022.geometry}
        material={materials["gris osciu.001"]}
        position={[9.717, 1.114, -9.974]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.663, -0.6, -0.802]}
      />
      <mesh
        geometry={nodes.Cubo023.geometry}
        material={materials.cafe}
        position={[9.762, 3.088, -10.003]}
        scale={[0.114, 1.823, 0.114]}
      />
      <mesh
        geometry={nodes.Cubo024.geometry}
        material={materials.arbol}
        position={[9.762, 1.961, -10.003]}
        scale={0.454}
      />
      <mesh
        geometry={nodes.Cubo025.geometry}
        material={materials.arbol}
        position={[9.762, 3.163, -10.003]}
        scale={0.351}
      />
      <mesh
        geometry={nodes.Cubo026.geometry}
        material={materials.arbol}
        position={[9.762, 4.196, -10.003]}
        scale={0.351}
      />
      <mesh
        geometry={nodes.Cubo027.geometry}
        material={materials.arbol}
        position={[9.762, 5.232, -10.003]}
        scale={0.351}
      />
      <mesh
        geometry={nodes.Rosca.geometry}
        material={materials.arbol2}
        position={[8.108, 8.286, -12.612]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1, 1.474, 1]}
      />
      <mesh
        geometry={nodes.Cubo028.geometry}
        material={materials.negro}
        position={[8.108, 7.886, -10.922]}
        scale={[-0.102, -0.102, -0.631]}
      />
      <mesh
        geometry={nodes.Cubo029.geometry}
        material={materials.negro}
        position={[8.108, 8.507, -10.922]}
        scale={[-0.102, -0.102, -0.631]}
      />
      <mesh
        geometry={nodes.Cubo030.geometry}
        material={materials["Material.003"]}
        position={[7.9, 4.884, -10.926]}
        scale={0.415}
      />
      <mesh
        geometry={nodes.Cubo031.geometry}
        material={materials["Material.005"]}
        position={[36.073, 0.149, 0.176]}
        scale={[10.061, 0.188, 28.854]}
      />
      <mesh
        geometry={nodes.Cubo032.geometry}
        material={materials.blenco}
        position={[35.741, 0.362, 25.138]}
        scale={[0.885, 0.017, 2.539]}
      />
      <mesh
        geometry={nodes.Cubo033.geometry}
        material={materials.blenco}
        position={[35.804, 0.362, 14.503]}
        scale={[0.885, 0.017, 2.539]}
      />
      <mesh
        geometry={nodes.Cubo034.geometry}
        material={materials.blenco}
        position={[35.93, 0.362, 3.994]}
        scale={[0.885, 0.017, 2.539]}
      />
      <mesh
        geometry={nodes.Cubo035.geometry}
        material={materials.blenco}
        position={[36.021, 0.362, -7.572]}
        scale={[0.885, 0.017, 2.539]}
      />
      <mesh
        geometry={nodes.Cubo036.geometry}
        material={materials.blenco}
        position={[36.147, 0.362, -18.081]}
        scale={[0.885, 0.017, 2.539]}
      />
      <mesh
        geometry={nodes.Cubo037.geometry}
        material={materials.blenco}
        position={[36.256, 0.362, -27.168]}
        scale={[0.885, 0.017, 1.488]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[24.499, 0.161, -14.847]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.359, -0.15, -1.299]}
      />
      <group
        position={[24.275, 0.92, 12.551]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.706, -0.639, -0.854]}
      >
        <mesh
          geometry={nodes.Cubo043_1.geometry}
          material={materials["gris osciu.001"]}
        />
        <mesh geometry={nodes.Cubo043_2.geometry} material={materials.blenco} />
      </group>
      <mesh
        geometry={nodes.Cubo039.geometry}
        material={materials.arbol}
        position={[24.282, 1.644, 12.55]}
        scale={0.068}
      />
      <group
        position={[24.275, 0.92, 10.065]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.706, -0.639, -0.854]}
      >
        <mesh
          geometry={nodes.Cubo045_1.geometry}
          material={materials["Material.001"]}
          receiveShadow
          castShadow
        />
        <mesh
          geometry={nodes.Cubo045_2.geometry}
          material={materials["Material.002"]}
          receiveShadow
          castShadow
        />
      </group>
      <mesh
        geometry={nodes.Cubo041.geometry}
        material={materials.arbol2}
        position={[24.282, 1.644, 10.064]}
        scale={0.068}
      />
      <group
        position={[-5.658, 14.235, 25.557]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo051_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo051_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[3.626, 10.836, 26.072]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo052_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo052_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-0.838, 12.283, 17.481]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo053_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo053_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[3.16, 7.567, -20.851]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-1.657, -4.384, -1.692]}
      >
        <mesh geometry={nodes.Cubo054_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo054_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-12.939, 14.235, -24.965]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo055_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo055_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[0.471, 10.836, -25.785]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo056_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo056_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-5.813, 12.283, -18.965]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo057_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo057_2.geometry} material={materials.cafe} />
      </group>
      <group position={[25.207, 0.695, 15.477]} scale={-0.442}>
        <mesh
          geometry={nodes.Cubo058_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cubo058_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.004"]}
        position={[11.587, 0, 75.407]}
        rotation={[0, 0, -Math.PI]}
        scale={[-29.373, -0.144, -28.081]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.004"]}
        position={[-70.742, 0, 75.407]}
        rotation={[0, 0, -Math.PI]}
        scale={[-29.373, -0.144, -28.081]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.004"]}
        position={[-70.742, 0, 0.888]}
        rotation={[0, 0, -Math.PI]}
        scale={[-29.373, -0.144, -28.081]}
      />
      <mesh
        geometry={nodes.Plano002.geometry}
        material={materials.piso}
        position={[-26.853, -0.142, 25.796]}
        scale={132.305}
      />
      <group
        position={[6.58, 10.864, 56.9]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo059_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo059_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-11.999, 14.235, 54.115]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo060_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo060_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[3.8, 10.836, 66.371]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo061_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo061_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-0.838, 12.283, 53.587]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo062_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo062_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-49.842, 10.836, 57.81]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo064_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo064_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-46.267, 12.283, 51.49]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo065_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo065_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-61.572, 14.235, 16.233]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo066_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo066_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-52.113, 10.836, 20.942]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo067_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo067_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-48.539, 12.283, 14.623]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo068_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo068_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-3.441, 10.864, 84.973]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo069_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo069_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-8.25, 14.235, 72.753]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo070_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo070_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-12.923, 10.836, 82.229]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo071_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo071_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-0.157, 12.283, 77.543]}
        rotation={[0, -1.567, -Math.PI]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo072_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo072_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-47.828, 10.864, 79.731]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo073_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo073_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-58.747, 14.235, 67.511]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo074_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo074_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-63.42, 10.836, 76.987]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo075_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo075_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-50.653, 12.283, 72.301]}
        rotation={[0, -1.567, -Math.PI]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo076_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo076_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-86.776, 14.235, 64.575]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo077_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo077_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-77.317, 10.836, 69.283]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo078_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo078_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-73.743, 12.283, 62.964]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo079_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo079_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-81.414, 10.864, 91.205]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo080_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo080_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-86.223, 14.235, 78.985]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo081_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo081_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-90.896, 10.836, 88.461]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo082_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo082_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-78.129, 12.283, 83.775]}
        rotation={[0, -1.567, -Math.PI]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo083_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo083_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-86.028, 14.235, 10.195]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo084_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo084_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-76.57, 10.836, 14.903]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo085_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo085_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-72.995, 12.283, 8.584]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo086_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo086_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-51.824, 10.864, 4.249]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo087_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo087_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-56.633, 14.235, -22.123]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo088_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo088_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-61.307, 10.836, 1.504]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo089_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo089_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-48.54, 12.283, -3.182]}
        rotation={[0, -1.567, -Math.PI]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo090_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo090_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-75.204, 10.836, -6.2]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo091_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo091_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-71.63, 12.283, -12.519]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo092_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo092_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-60.61, 14.235, 86.723]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo093_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo093_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-51.151, 10.836, 91.432]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo094_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo094_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-63.202, 14.235, 97.813]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo096_1.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo096_2.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-4.119, 10.864, 100.867]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo097.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo097_1.geometry} material={materials.cafe} />
      </group>
      <group
        position={[16.589, 14.235, 88.646]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-3.124, -8.263, -3.189]}
      >
        <mesh geometry={nodes.Cubo098.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo098_1.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-13.601, 10.836, 98.122]}
        rotation={[0, 0.004, -Math.PI]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo099.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo099_1.geometry} material={materials.cafe} />
      </group>
      <group
        position={[-0.835, 12.283, 93.437]}
        rotation={[0, -1.567, -Math.PI]}
        scale={[-2.682, -7.095, -2.738]}
      >
        <mesh geometry={nodes.Cubo100.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo100_1.geometry} material={materials.cafe} />
      </group>
      <group
        position={[18.62, 10.864, 56.9]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-2.417, -6.394, -2.468]}
      >
        <mesh geometry={nodes.Cubo101.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo101_1.geometry} material={materials.cafe} />
      </group>
      <group
        position={[23.442, 5.305, 26.782]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-1.145, -3.029, -1.169]}
      >
        <mesh geometry={nodes.Cubo102.geometry} material={materials.arbol} />
        <mesh geometry={nodes.Cubo102_1.geometry} material={materials.cafe} />
      </group>
      <group position={[25.207, 0.695, -15.158]} scale={-0.442}>
        <mesh
          geometry={nodes.Cubo103.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cubo103_1.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[7.652, 21.519, -8.242]} scale={[0.092, 0.304, 0.092]}>
        <mesh geometry={nodes.Cubo104.geometry} material={materials.negro} />
        <mesh
          geometry={nodes.Cubo104_1.geometry}
          material={materials["blanco 2"]}
        />
      </group>
      <group position={[7.652, 21.519, 8.244]} scale={[0.092, 0.304, 0.092]}>
        <mesh geometry={nodes.Cubo105.geometry} material={materials.negro} />
        <mesh
          geometry={nodes.Cubo105_1.geometry}
          material={materials["blanco 2"]}
        />
      </group>
      <group position={[6.537, 21.492, -9.272]} scale={[0.092, 0.304, 0.092]}>
        <mesh geometry={nodes.Cubo106.geometry} material={materials.negro} />
        <mesh
          geometry={nodes.Cubo106_1.geometry}
          material={materials["blanco 2"]}
        />
      </group>
      <group position={[-6.019, 21.492, -9.272]} scale={[0.092, 0.304, 0.092]}>
        <mesh geometry={nodes.Cubo107.geometry} material={materials.negro} />
        <mesh
          geometry={nodes.Cubo107_1.geometry}
          material={materials["blanco 2"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/casaDonuts.glb");
